services:
  postgres:
    container_name: postgres-sql-bsn # 컨테이너의 고유 이름 지정
    image: postgres # 공식 PostgreSQL 이미지 사용
    environment:
      POSTGRES_USER: username # 데이터베이스 접속 사용자명
      POSTGRES_PASSWORD: password # 데이터베이스 접속 비밀번호
      PGDATA: /var/lib/postgresql/data # This is the path where the data will be stored
      POSTGRES_DB: book_social_network # 생성할 데이터베이스 이름
    volumes:
      - postgres:/data/postgres # 볼륨 마운트: 데이터 영속성 보장
    ports:
      - 5432:5432 # public port:container port
    networks: # This is the network that the container will be connected to. Want all containers to be connected to the same network
      - spring-demo
    restart: unless-stopped # 컨테이너가 비정상 종료될 경우 자동 재시작
  mail-dev:
    container_name: mail-dev-bsn # 메일 서비스 컨테이너 이름
    image: maildev/maildev # 개발용 SMTP 서버 및 웹 인터페이스 제공 이미지
    ports:
      - 1080:1080 # by docs, this is the port that maildev uses
      - 1025:1025 # used by our spring application

networks:
  spring-demo:
    driver: bridge # 컨테이너 간 통신을 위한 표준 네트워크 드라이버

volumes:
  postgres:
    driver: local # 호스트 시스템에 데이터 저장을 위한 로컬 볼륨 드라이버
