apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-network.fullname" . }}
  labels:
    {{- include "book-network.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "book-network.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-network.fullname" . }}-metrics
  labels:
    {{- include "book-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/api/v1/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "book-network.selectorLabels" . | nindent 4 }}
{{- end }}